# Generated by Django 6.0.3 on 2026-04-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='rev_dest',
            field=models.IntegerField(blank=True, help_text='Depósito asignado (art_dest)', null=True),
        ),
    ]
