# Generated by Django 6.0.3 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('gen', models.AutoField(primary_key=True, serialize=False)),
                ('gen_nomb', models.CharField(blank=True, help_text='Nombre de la empresa', max_length=150)),
                ('gen_logo', models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'General',
                'verbose_name_plural': 'General',
            },
        ),
        migrations.AlterModelOptions(
            name='confirmacionventa',
            options={'ordering': ['con_reve_id', 'con_marc_id', 'con_rubr_id'], 'verbose_name': 'Confirmación de Venta', 'verbose_name_plural': 'Confirmaciones de Venta'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['pci_codi_id', 'loc_nomb'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['mar_codi_id', 'rub_nomb'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterModelOptions(
            name='subrubro',
            options={'ordering': ['sru_rubr_id', 'sru_nomb'], 'verbose_name': 'Sub-rubro', 'verbose_name_plural': 'Sub-rubros'},
        ),
        migrations.RemoveIndex(
            model_name='confirmacionventa',
            name='gestion_con_con_rev_07d86e_idx',
        ),
        migrations.RemoveIndex(
            model_name='confirmacionventa',
            name='gestion_con_con_rev_199b44_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidos',
            name='gestion_ped_rev_cod_70fdb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='gestion_sto_stk_art_872285_idx',
        ),
        migrations.AddField(
            model_name='revendedor',
            name='rev_logo',
            field=models.ImageField(blank=True, help_text='Logo del revendedor', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='art_plis',
            field=models.DecimalField(decimal_places=2, help_text='Precio de lista', max_digits=12),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='art_prec',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=12),
        ),
        migrations.AlterField(
            model_name='confirmacionventa',
            name='con_porc',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje/Descuento', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_monf',
            field=models.DecimalField(decimal_places=2, help_text='Monto final total', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_plis',
            field=models.DecimalField(decimal_places=2, help_text='Precio lista', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_prec',
            field=models.DecimalField(decimal_places=2, help_text='Precio final/pactado', max_digits=12),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='rev_porc',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje/Comisión', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='confirmacionventa',
            index=models.Index(fields=['con_reve_id', 'con_marc_id'], name='gestion_con_con_rev_07d86e_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmacionventa',
            index=models.Index(fields=['con_reve_id', 'con_arti_id'], name='gestion_con_con_rev_199b44_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['rev_codi_id', '-pov_fchc'], name='gestion_ped_rev_cod_70fdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stk_arti_id', 'stk_depo'], name='gestion_sto_stk_art_872285_idx'),
        ),
    ]
