# Generated by Django 6.0.3 on 2026-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicioniva',
            name='civ_porc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA (ej: 21.0 o 10.5)', max_digits=5),
        ),
    ]
