# Generated by Django 6.0.3 on 2026-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_revendedor_rev_dest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['ped_exp', '-pov_codi'], name='gestion_ped_exp_pov_idx'),
        ),
    ]
