# Generated by Django 6.0.3 on 2026-04-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_condicioniva_civ_porc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicioniva',
            name='civ_porc',
        ),
    ]
