# Generated by Django 6.0.3 on 2026-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_general_alter_confirmacionventa_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='pov_che3',
            new_name='pov_cheq',
        ),
    ]
