# Generated by Django 6.0.3 on 2026-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_condicioniva_civ_porc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='art_tiva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
