# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_pov_che3_pedidos_pov_cheq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='art_plis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de lista', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='art_prec',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='rev_porc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje/Comisión', max_digits=5, null=True),
        ),
    ]
