# Generated by Django 6.0.3 on 2026-04-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pedidos_gestion_ped_exp_pov_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='art_mode',
        ),
    ]
