# Generated by Django 6.0.3 on 2026-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_articulos_art_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='rev_actv',
            field=models.BooleanField(default=True, help_text='Activo', null=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='rev_tele',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('art_codi', 'art_ncha', 'art_nmot', 'art_ncer'), name='unique_stock_unidad'),
        ),
    ]
