# Generated by Django 6.0.3 on 2026-04-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_articulos_art_tiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='rub_codi',
        ),
    ]
