# Generated by Django 6.0.3 on 2026-03-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_articulos_art_plis_alter_articulos_art_prec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='mar_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='gestion.marca'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='rub_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='gestion.rubro'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='com_nomb',
            field=models.CharField(max_length=100),
        ),
    ]
