# Generated by Django 6.0.3 on 2026-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_revendedor_rev_actv_alter_revendedor_rev_tele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='loc_cpos',
            field=models.IntegerField(blank=True, help_text='Código postal', null=True),
        ),
    ]
