# Generated by Django 6.0.3 on 2026-05-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_localidad_loc_cpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroRevendedor',
            fields=[
                ('fr_codi', models.AutoField(primary_key=True, serialize=False)),
                ('fr_nomb', models.CharField(help_text='Nombre del filtro (ej: Sucursal, Depósito, etc.)', max_length=100)),
                ('fr_tipo', models.CharField(help_text='Tipo de filtro (ej: sucursal, bodega, etc.)', max_length=50)),
                ('fr_desc', models.TextField(blank=True, help_text='Descripción opcional', null=True)),
                ('fr_fcre', models.DateTimeField(auto_now_add=True)),
                ('fr_fmod', models.DateTimeField(auto_now=True)),
                ('rev_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_personalizados', to='gestion.revendedor')),
            ],
            options={
                'verbose_name': 'Filtro Revendedor',
                'verbose_name_plural': 'Filtros Revendedor',
                'ordering': ['rev_codi', 'fr_nomb'],
                'unique_together': {('rev_codi', 'fr_nomb')},
            },
        ),
        migrations.CreateModel(
            name='ValorFiltroStock',
            fields=[
                ('vfs_codi', models.AutoField(primary_key=True, serialize=False)),
                ('vfs_valor', models.CharField(help_text='Valor del filtro (ej: Sucursal 1, Bodega A, etc.)', max_length=100)),
                ('vfs_fcre', models.DateTimeField(auto_now_add=True)),
                ('vfs_fmod', models.DateTimeField(auto_now=True)),
                ('fr_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_stock', to='gestion.filtrorevendedor')),
                ('stk_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_filtros', to='gestion.stock')),
            ],
            options={
                'verbose_name': 'Valor Filtro Stock',
                'verbose_name_plural': 'Valores Filtros Stock',
                'ordering': ['stk_codi', 'fr_codi'],
                'unique_together': {('stk_codi', 'fr_codi')},
            },
        ),
    ]
