# Generated by Django 6.0.3 on 2026-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rebuild_stock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='gestion_sto_art_cod_f5b60a_idx',
            old_name='gestion_sto_art_cod_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='gestion_sto_art_nch_a3f91e_idx',
            old_name='gestion_sto_art_nch_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='gestion_sto_art_des_c1a9f6_idx',
            old_name='gestion_sto_art_des_idx',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='art_tprec',
            field=models.CharField(choices=[('F', 'Precio Final'), ('N', 'Precio Neto')], default='F', max_length=1),
        ),
    ]
