# Generated by Django 6.0.3 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_filtrorevendedor_valorfiltrostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrorevendedor',
            name='fr_desc',
            field=models.TextField(blank=True, help_text='Descripcion opcional', null=True),
        ),
        migrations.AlterField(
            model_name='filtrorevendedor',
            name='fr_nomb',
            field=models.CharField(help_text='Nombre del filtro (ej: Sucursal, Deposito, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='filtrorevendedor',
            name='fr_tipo',
            field=models.CharField(help_text='Tipo de filtro (ej: sucursal, Deposito, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='valorfiltrostock',
            name='vfs_valor',
            field=models.CharField(help_text='Valor del filtro (ej: Sucursal 1, DEstino 2, etc.)', max_length=100),
        ),
    ]
