# Generated by Django 6.0.3 on 2026-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_filtrorevendedor_fr_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportarDatos',
            fields=[
                ('imp_codi', models.AutoField(primary_key=True, serialize=False)),
                ('imp_dato1', models.FileField(blank=True, help_text='PDF de Cuentas Bancarias', null=True, upload_to='importaciones/bancos/')),
                ('imp_dato2', models.FileField(blank=True, help_text='PDF de Datos Financiera', null=True, upload_to='importaciones/financiera/')),
                ('imp_dato3', models.FileField(blank=True, help_text='Archivo adicional 3', null=True, upload_to='importaciones/otros/')),
                ('imp_dato4', models.FileField(blank=True, help_text='Archivo adicional 4', null=True, upload_to='importaciones/otros/')),
                ('imp_dato5', models.FileField(blank=True, help_text='Archivo adicional 5', null=True, upload_to='importaciones/otros/')),
                ('imp_fcre', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('imp_fmod', models.DateTimeField(auto_now=True, help_text='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Importar Datos',
                'verbose_name_plural': 'Importar Datos',
                'ordering': ['-imp_fcre'],
            },
        ),
    ]
