# Generated by Django 6.0.3 on 2026-03-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_rebuild_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='gen',
            new_name='gen_codi',
        ),
    ]
