# Generated by Django 6.0.3 on 2026-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_rename_gen_general_gen_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ped_exp',
            field=models.BooleanField(default=False, help_text='Indica si el pedido ya fue exportado a Genexus'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_fexp',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que el pedido fue exportado', null=True),
        ),
    ]
