# Generated by Django 6.0.3 on 2026-03-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_pedidos_ped_exp_pedidos_ped_fexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pov_icdo',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pov_cont',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contado/Efectivo', max_digits=12, null=True),
        ),
    ]
