# Generated by Django 6.0.3 on 2026-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_pedidos_pov_icdo_pedidos_pov_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pov_cheq',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cheques (POV_CHE3)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_cont',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contado/Efectivo', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_impc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe crédito', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_monf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto final', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_plis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio lista', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_ppag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pago contado/efectivo', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_tarc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarjeta crédito', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pov_tran',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transferencia', max_digits=15, null=True),
        ),
    ]
