# Generated by Django 6.0.3 on 2026-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_pedidos_pov_cheq_alter_pedidos_pov_cont_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_cuit',
            field=models.CharField(blank=True, help_text='CUIT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_emai',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
