# Generated by Django 6.0.3 on 2026-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_clientes_cli_cuit_alter_clientes_cli_emai'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='gen_loge',
            field=models.ImageField(blank=True, help_text='Logo de BrixSoft', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_logo',
            field=models.ImageField(blank=True, help_text='Logo de Centro Motos', null=True, upload_to='logos/'),
        ),
    ]
