# Generated by Django 6.0.3 on 2026-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_create_general_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='rev_logo',
            field=models.ImageField(blank=True, help_text='Logo del revendedor', null=True, upload_to='revendedores/'),
        ),
    ]
