# Generated by Django 6.0.3 on 2026-03-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_add_comprobante_fields'),
        ('gestion', '0017_alter_revendedor_rev_logo'),
    ]

    operations = [
    ]
