# Generated by Django 6.0.3 on 2026-04-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_hash_revendedor_passwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubro',
            options={'ordering': ['rub_codi_id', 'sru_nomb'], 'verbose_name': 'Sub-rubro', 'verbose_name_plural': 'Sub-rubros'},
        ),
        migrations.RenameField(
            model_name='subrubro',
            old_name='sru_rubr',
            new_name='rub_codi',
        ),
        migrations.AlterUniqueTogether(
            name='subrubro',
            unique_together={('rub_codi', 'sru_nomb')},
        ),
    ]
