# Generated by Django 6.0.3 on 2026-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_rename_subrubro_sru_rubr_to_rub_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='art_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='col_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='com_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='condicioniva',
            name='civ_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='confirmacionventa',
            name='con_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='loc_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pci_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='rev_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='rub_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stk_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subrubro',
            name='sru_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
