# Generated by Django 6.0.3 on 2026-04-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_articulos_art_codi_alter_clientes_cli_codi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['rub_nomb'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='mar_codi',
        ),
    ]
